<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZF2TwitterBootstrap\Form\View\Helper\FormLabel' => __DIR__ . '/src/ZF2TwitterBootstrap/Form/View/Helper/FormLabel.php',
    'ZF2TwitterBootstrap\Module'                     => __DIR__ . '/src/ZF2TwitterBootstrap/Module.php',
);